### ISSUE TITLE
Feature Request: Add custom CSS

### ISSUE THREAD

**Issue by atraining** [gera2ld/markmap#39]
We would like to add CSS so we can customize the UI. E. g. like https://codepen.io/atraining/full/ExKgmbM

Example

```
<style>
#mindmap {
  width: 100vw;
  height: 100vh;
}
#mindmap path {
    stroke: black;
}

#mindmap circle {
    stroke: #44b78b;
}

#mindmap circle {
    fill: #44b78b;
}

#mindmap rect {
    fill: black;
}

</style>
```

**Comment by gera2ld** [comment]
The API supports custom CSS but the CLI does not.

```js
Markmap.create('#markmap', {
  style: id => customCss,
}, data);
```

Also there is a `color` option to decide the color of each circle and line.
Does that satisfy your need?

**Comment by atraining** [comment]
Hi Gerald! Thank you for your quick response. As we are currently using your "try it out" page, it does not really solve our needs as we would need to host markmap ourselves. But if this is the path to go, we can do it :+1: 

At [Konfuzio](https://www.konfuzio.com) we love your tool :)

Thank your for the great work!

**Comment by eyssette** [comment]
I've managed to customize a bit the CSS (and integrate Markmap into Svelte).
[https://svelte.dev/repl/9499dbcf3f3240e4af42e38ab19cc9ea?version=3.47.0](https://svelte.dev/repl/9499dbcf3f3240e4af42e38ab19cc9ea?version=3.47.0)

But it would be great if markmap-view could generate some specific classes for the different nodes level, so that we could have more control over the appareance.

Thanks for your wonderful app!
